# {{SERVICE_NAME}} - {{DESCRIPTION}}
# Generated by GX Genesis | Team: {{TEAM}} | Tier: {{TIER}} | Eco: {{ECO_NAME}}
FROM python:3.11-slim

# Labels for Galaxy platform
LABEL service.name="{{SERVICE_NAME}}" \
      service.tier="{{TIER}}" \
      service.workload="{{TIER}}" \
      service.team="{{TEAM}}" \
      service.eco="{{ECO_NAME}}" \
      galaxy.io/managed-by="galaxy"

# Set working directory
WORKDIR /app

# Install system dependencies for app services
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies (customize per service)
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pydantic \
    httpx

# Copy source code
COPY src/ ./src/

# Create non-root user for security
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port (Galaxy standard: 3000)
EXPOSE 3000

# Enhanced health check with Galaxy service metadata
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f -H "X-Service-Name: {{SERVICE_NAME}}" -H "X-Service-Team: {{TEAM}}" -H "X-Service-Tier: {{TIER}}" -H "X-Service-Eco: {{ECO_NAME}}" -H "X-Galaxy-Managed: true" http://localhost:3000/health || exit 1

# Run with Galaxy-compatible settings
CMD ["uvicorn", "src.galaxy:app", "--host", "0.0.0.0", "--port", "3000"]
