# app-smoke-api - Smoke test API service
# Generated by GX Genesis | Team: team1 | Tier: app | Eco: gx-smoke
FROM python:3.11-slim

# Labels for Galaxy platform
LABEL service.name="app-smoke-api" \
      service.tier="app" \
      service.workload="app" \
      service.team="team1" \
      service.eco="gx-smoke" \
      galaxy.io/managed-by="galaxy"

# Set working directory
WORKDIR /app

# Install system dependencies for app services
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies (customize per service)
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pydantic \
    httpx

# Copy source code
COPY src/ ./src/

# Create non-root user for security
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port (Galaxy standard: 3000)
EXPOSE 3000

# Enhanced health check with Galaxy service metadata
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f -H "X-Service-Name: app-smoke-api" -H "X-Service-Team: team1" -H "X-Service-Tier: app" -H "X-Service-Eco: gx-smoke" -H "X-Galaxy-Managed: true" http://localhost:3000/health || exit 1

# Run with Galaxy-compatible settings
CMD ["uvicorn", "src.galaxy:app", "--host", "0.0.0.0", "--port", "3000"]
